### ISSUE TITLE
Bulkhead resource count produces error

### ISSUE THREAD

**Issue by miry** [Shopify/semian#414]
During work on examples, i found to problem to print the `count` value:

<details>
  <summary>Click me: Error stack trace</summary>

<pre>
examples/net_http/07_bulkhead_in_fork.rb:87:in `count': semctl() failed, errno: 22 (Invalid argument) (Semian::SyscallError)
	from examples/net_http/07_bulkhead_in_fork.rb:87:in `block in <main>'
	from examples/net_http/07_bulkhead_in_fork.rb:63:in `fork'
	from examples/net_http/07_bulkhead_in_fork.rb:63:in `<main>'
/usr/local/lib/ruby/3.1.0/socket.rb:1214:in `__connect_nonblock': Failed to open TCP connection to example.com:81 (Cannot assign requested address - connect(2) for [2606:2800:220:1:248:1893:25c8:1946]:81) (Errno::EADDRNOTAVAIL)
	from /usr/local/lib/ruby/3.1.0/socket.rb:1214:in `connect_nonblock'
	from /usr/local/lib/ruby/3.1.0/socket.rb:56:in `connect_internal'
	from /usr/local/lib/ruby/3.1.0/socket.rb:137:in `connect'
	from /usr/local/lib/ruby/3.1.0/socket.rb:642:in `block in tcp'
	from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `each'
	from /usr/local/lib/ruby/3.1.0/socket.rb:227:in `foreach'
	from /usr/local/lib/ruby/3.1.0/socket.rb:632:in `tcp'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:998:in `connect'
	from /workspace/lib/semian/net_http.rb:96:in `block in connect'
	from /workspace/lib/semian/adapter.rb:74:in `mark_resource_as_acquired'
	from /workspace/lib/semian/adapter.rb:38:in `block in acquire_semian_resource'
	from /workspace/lib/semian/protected_resource.rb:30:in `block (2 levels) in acquire'
	from /workspace/lib/semian/protected_resource.rb:59:in `block in acquire_bulkhead'
	from /workspace/lib/semian/protected_resource.rb:58:in `acquire'
	from /workspace/lib/semian/protected_resource.rb:58:in `acquire_bulkhead'
	from /workspace/lib/semian/protected_resource.rb:28:in `block in acquire'
	from /workspace/lib/semian/protected_resource.rb:43:in `acquire_circuit_breaker'
	from /workspace/lib/semian/protected_resource.rb:27:in `acquire'
	from /workspace/lib/semian/adapter.rb:37:in `acquire_semian_resource'
	from /workspace/lib/semian/net_http.rb:96:in `connect'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:976:in `do_start'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:965:in `start'
	from /usr/local/lib/ruby/3.1.0/net/http.rb:627:in `start'
	from examples/net_http/07_bulkhead_in_fork.rb:121:in `block in <main>'
	from examples/net_http/07_bulkhead_in_fork.rb:93:in `fork'
	from examples/net_http/07_bulkhead_in_fork.rb:93:in `<main>'
</pre>
</details>

**Comment by miry** [comment]
it was problem to use wrong semian.so, that was built for different arch.
